Booky/Areas/Admin/Controllers/AccountsController.cs
using Booky.Resources;
using Domain.Constants;
using Domain.Entities;
using Infrastructure.Data;
using Infrastructure.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Booky.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Permissions.Accounts.View)]
    public class AccountsController : Controller
    {
        #region Declaration
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly BookyDbContext _dbContext;
        private readonly SignInManager<ApplicationUser> _signInManager;
        #endregion

        #region Constructor
        public AccountsController(RoleManager<IdentityRole> roleManager,
            UserManager<ApplicationUser> userManager,
            BookyDbContext dbContext, SignInManager<ApplicationUser> signInManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _dbContext = dbContext;
            _signInManager = signInManager;
        }

        #endregion

        #region Actions

        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);

                if (result.Succeeded)
                    return RedirectToAction("Index", "Home");
                else
                    ViewBag.LoginErr = false;
            }
            return View(model);

        }

        [Authorize(Permissions.Accounts.View)]
        public async Task<IActionResult> Register()
        {
            var roles = await _roleManager.Roles.OrderBy(r => r.Name).ToListAsync();
            var users = await _dbContext.VwUsers.OrderBy(u => u.Role).ToListAsync();

            var model = new RegisterViewModel
            {
                Roles = roles,
                NewRegister = new NewRegister(),
                Users = users

            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Permissions.Accounts.Create)]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Register", "Accounts");

            model.NewRegister.UserImage = NewImageUrl(model);

            var user = new ApplicationUser
            {
                Id = model.NewRegister.Id,
                Name = model.NewRegister.Name,
                Email = model.NewRegister.Email,
                UserImage = model.NewRegister.UserImage,
                UserName = model.NewRegister.Email,
                IsActive = model.NewRegister.IsActive,
            };

            //Create
            if (user.Id == null)
            {
                user.Id = Guid.NewGuid().ToString();
                var result = await _userManager.CreateAsync(user, model.NewRegister.Password);

                if (result.Succeeded)
                {
                    var roleResult = await _userManager.AddToRoleAsync(user, model.NewRegister.RoleName);
                    if (roleResult.Succeeded)
                        SessionMsgs(Helper.Success, WebResource.Save, WebResource.SaveUserMsg);
                    else
                        SessionMsgs(Helper.Error, WebResource.SaveErr, WebResource.SaveRoleErrMsg);
                }
                else
                    SessionMsgs(Helper.Error, WebResource.RegisterErr, WebResource.RegisterErrMsg);
            }
            //Edit
            else
            {
                var oldUser = await _userManager.FindByIdAsync(user.Id);

                oldUser.Name = model.NewRegister.Name;
                oldUser.Email = model.NewRegister.Email;
                oldUser.UserImage = model.NewRegister.UserImage;
                oldUser.UserName = model.NewRegister.Email;
                oldUser.IsActive = model.NewRegister.IsActive;

                var result = await _userManager.UpdateAsync(oldUser);

                if (result.Succeeded)
                {
                    var oldRole = await _userManager.GetRolesAsync(oldUser);
                    await _userManager.RemoveFromRolesAsync(oldUser, oldRole);
                    var addRoleResult = await _userManager.AddToRoleAsync(oldUser, model.NewRegister.RoleName);

                    if (addRoleResult.Succeeded)
                        SessionMsgs(Helper.Success, WebResource.Edit, WebResource.EditUserMsg);
                    else
                        SessionMsgs(Helper.Error, WebResource.EditErr, WebResource.EditRoleErrMsg);
                }
                else
                    SessionMsgs(Helper.Error, WebResource.EditErr, WebResource.EditUserErrMsg);
            }

            return RedirectToAction("Register", "Accounts");
        }

        private string NewImageUrl(RegisterViewModel model)
        {
            string? oldImageUrl = model.NewRegister.UserImage;
            string? newImageUrl = UploadImage();

            if (newImageUrl != null)
            {
                DeleteImage(oldImageUrl);
            }
            else
            {
                newImageUrl = oldImageUrl ?? Helper.DefaultImage;
            }
            return newImageUrl;
        }
        private string? UploadImage()
        {
            var ImageFile = HttpContext.Request.Form.Files.SingleOrDefault(f => f.Name == "ImageFile");
            if (ImageFile != null)
            {
                var imageName = ImageFile.FileName;

                string uniqueImageName = Guid.NewGuid().ToString() + Path.GetExtension(imageName);

                var imagePath = Path.Combine(@"wwwroot/", Helper.SaveUserImgPath, uniqueImageName);
                ImageFile.CopyTo(new FileStream(imagePath, FileMode.Create));

                return uniqueImageName;
            }
            else
            {
                return null;
            }
        }
        private void DeleteImage(string? OldImageUrl)
        {
            if (OldImageUrl != null && OldImageUrl != Helper.DefaultImage && OldImageUrl != Guid.Empty.ToString())
            {
                var OldImage = Path.Combine(@"wwwroot/", Helper.SaveUserImgPath, OldImageUrl);

                if (System.IO.File.Exists(OldImage))
                    System.IO.File.Delete(OldImage);
            }
        }


        [Authorize(Permissions.Accounts.Delete)]
        public async Task<IActionResult> DeleteUser(string Id)
        {
            var user = await _userManager.Users.SingleOrDefaultAsync(u => u.Id == Id);

            if (user == null)
                return NotFound();

            DeleteImage(user.UserImage);
            var result = await _userManager.DeleteAsync(user);

            //if(!result.Succeeded)

            return RedirectToAction(nameof(Register));
        }

        [Authorize(Permissions.Accounts.Create)]
        public async Task<IActionResult> ChangePassword(RegisterViewModel model)
        {
            if (model.ChangePassword.Id == _userManager.GetUserId(User)
                || User.IsInRole("SuperAdmin") || User.IsInRole("Admin"))
            {
                var user = await _userManager.FindByIdAsync(model.ChangePassword.Id);

                if (user == null)
                    return RedirectToAction(nameof(Register));

                await _userManager.RemovePasswordAsync(user);

                var result = await _userManager.AddPasswordAsync(user, model.ChangePassword.NewPassword);

                if (result.Succeeded)
                    SessionMsgs(Helper.Success, WebResource.Save, WebResource.ChangePasswordSave);
                else
                    SessionMsgs(Helper.Error, WebResource.SaveErr, WebResource.ChangePasswordErr);

                return RedirectToAction(nameof(Register));
            }

            TempData["Access"] = "false";
            return RedirectToAction(nameof(Register));
        }

        [Authorize(Permissions.Roles.View)]
        public async Task<IActionResult> Roles()
        {
            var roles = await _roleManager.Roles.OrderBy(r => r.Name).ToListAsync();
            return View(new RolesViewModel { Roles = roles, NewRole = new NewRole() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Permissions.Roles.Create)]
        public async Task<IActionResult> Roles(RolesViewModel model)
        {
            if (!ModelState.IsValid)
                return RedirectToAction(nameof(Roles));

            var role = new IdentityRole
            {
                Id = model.NewRole.RoleId,
                Name = model.NewRole.RoleName
            };

            //Create new Role
            if (role.Id == null)
            {
                role.Id = Guid.NewGuid().ToString();
                var result = await _roleManager.CreateAsync(role);

                if (result.Succeeded)
                    SessionMsgs(Helper.Success, WebResource.Save, WebResource.SaveRoleMsg);
                else
                    SessionMsgs(Helper.Error, WebResource.SaveErr, WebResource.SaveRoleErrMsg);

            }
            //Edit an Existing Role
            else
            {
                var oldRole = await _roleManager.FindByIdAsync(role.Id);

                if (oldRole == null)
                    return NotFound();

                //oldRole.Id = role.Id;
                oldRole.Name = role.Name;
                var result = await _roleManager.UpdateAsync(oldRole);

                if (result.Succeeded)

Booky/Areas/Admin/Controllers/PermissionsController.cs
using System.Security.Claims;
using Domain.Constants;
using Infrastructure.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Booky.Areas.Admin.Controllers;

[Area("Admin")]
public class PermissionsController : Controller
{
    private readonly RoleManager<IdentityRole> _roleManager;

    public PermissionsController(RoleManager<IdentityRole> roleManager)
    {
        _roleManager = roleManager;
    }

    public async Task<IActionResult> ManagePermissions(string roleId)
    {
        var role = await _roleManager.FindByIdAsync(roleId);

        if (role == null) return NotFound();

        var roleClaims = _roleManager.GetClaimsAsync(role).Result.Select(c => c.Value).ToList();

        var allClaims = Permissions.GenerateAllPermissions();

        var allPermissions = allClaims.Select(p => new CheckBoxViewModel { Value = p }).ToList();

        foreach (var permission in allPermissions)
        {
            if (roleClaims.Any(c => c == permission.Value))
                permission.IsSelected = true;
        }

        var viewModel = new PermissionsViewModel
        {
            RoleId = role.Id,
            RoleName = role.Name,
            RoleClaims = allPermissions
        };

        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ManagePermissions(PermissionsViewModel model)
    {
        var role = await _roleManager.FindByIdAsync(model.RoleId);

        if (role == null) return NotFound();

        //Get all claims which already assigned to this role
        var roleClaims = await _roleManager.GetClaimsAsync(role);

        //Remover all claims from this role
        foreach (var claim in roleClaims)
        {
            await _roleManager.RemoveClaimAsync(role, claim);
        }

        //Get all selcted claims returned from view in model parameter 
        var selectedClaims = model.RoleClaims.Where(c => c.IsSelected).ToList();

        //Add all selected Claims to this role
        foreach (var claim in selectedClaims)
        {
            await _roleManager.AddClaimAsync(role, new Claim("Permission", claim.Value));
        }

        return RedirectToAction("Roles", "Accounts");
    }
}

Booky/Areas/Admin/Views/Accounts/Login.cshtml
@model LoginViewModel
@{
    ViewData["Title"] = "Login";
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Admin/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/Admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Admin/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Admin</b>LTE</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Sign in to start your session</p>

                <form asp-action="Login" method="post">
                    @if(ViewBag.LoginErr == false){
                        <span class="alert alert-danger w-100">@WebResource.LoginErr</span>
                        <br />
                    }
                    <div class="input-group mb-3">
                        <input type="email" class="form-control" placeholder="Email" asp-for="Email">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <span asp-validation-for="Email" class="text-danger"></span>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Password" asp-for="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <span asp-validation-for="Password" class="text-danger"></span>
                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                                <input type="checkbox" id="remember" asp-for="RememberMe">
                                <label for="remember">
                                    Remember Me
                                </label>
                            </div>
                        </div>
                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>

                <div class="social-auth-links text-center mb-3">
                    <p>- OR -</p>
                    <a href="#" class="btn btn-block btn-primary">
                        <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
                    </a>
                    <a href="#" class="btn btn-block btn-danger">
                        <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
                    </a>
                </div>
                <!-- /.social-auth-links -->

                <p class="mb-1">
                    <a href="#">I forgot my password</a>
                </p>
                <p class="mb-0">
                    <a href="register.html" class="text-center">Register a new membership</a>
                </p>
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/Admin/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>
</html>

Booky/Areas/Admin/Views/Accounts/Roles.cshtml
@model RolesViewModel
@{
    ViewData["Title"] = "Roles";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>@WebResource.RolesTableTitle</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-controller="Home"
                                asp-action="Index">@WebResource.HomePage</a></li>
                        <li class="breadcrumb-item active">@WebResource.ManageBook</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header d-flex align-items-center justify-content-start">
                        <h3 class="card-title">@WebResource.RolesTableTitle</h3>
                        <div class="card-tools">
                            @* @if (User.IsInRole("SuperAdmin") || User.IsInRole("Admin"))
                                { *@
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-outline-primary rounded-pill ml-5" data-toggle="modal"
                                data-target="#exampleModal" onclick="Reset()">
                                @WebResource.CreateNewRoleBtn
                            </button>
                            @* } *@
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="rolesTable" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <td>@WebResource.RoleName</td>
                                    <td>@WebResource.Events</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var role in Model.Roles)
                                {
                                    <tr>
                                        <td>
                                            @switch (role.Name)
                                            {
                                                case "SuperAdmin":
                                                    <span class="badge badge-danger"
                                            style="width:250px;height:25px;">@role.Name</span>
                                                    break;
                                                case "Admin":
                                                    <span class="badge badge-success"
                                            style="width:250px;height:25px;">@role.Name</span>
                                                    break;
                                                default:
                                                    <span class="badge badge-warning"
                                            style="width:250px;height:25px;">@role.Name</span>
                                                    break;
                                            }
                                        </td>
                                        @*@if(User.IsInRole("SuperAdmin") || User.IsInRole("Admin")){
                                            <td>
                                            <input type="button" class="btn btn-info btn-sm" onclick="Edit('@role.Id',
                                            '@role.Name')" value="@WebResource.EditBtn" data-toggle="modal"
                                            data-target="#exampleModal" />
                                            <input type="button" class="btn btn-danger btn-sm" onclick="Delete('@role.Id')"
                                            value="@WebResource.DeleteBtn" />
                                            </td>
                                            }*@
                                        <td>
                                            <input type="button" class="btn btn-info btn-sm"
                                            onclick="Edit('@role.Id', '@role.Name')" value="@WebResource.EditBtn"
                                            data-toggle="modal" data-target="#exampleModal" />

                                            <input type="button" class="btn btn-danger btn-sm" onclick="Delete('@role.Id')"
                                            value="@WebResource.DeleteBtn" />

                                            <a class="btn btn-success btn-sm" asp-action="ManagePermissions"
                                            asp-controller="Permissions" asp-route-roleId="@role.Id">
                                                @WebResource.AddPermissionsBtn
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>




<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="title">@WebResource.CreateNewRoleBtn</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-action="Roles" asp-controller="Accounts" method="post">
                    <div class="form-group">
                        <input type="text" hidden id="roleId" class="form-control" asp-for="NewRole.RoleId" />

                        <label asp-for="NewRole.RoleName" class="conrole-lable">@WebResource.RoleName</label>
                        <input type="text" id="roleName" class="form-control" asp-for="NewRole.RoleName" />
                        <span asp-validation-for="NewRole.RoleName" class="text-danger"></span>

                    </div>
                    <div class="modal-footer-rtl" style="padding:0 15px 15px 0">
                        <input type="submit" id="btnSave" class="btn btn-primary" value="@WebResource.SaveBtn" />
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">@WebResource.Close</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

@section Script{
@*@{
    var msgType = Context.Session.GetString("msgType");
    var title = Context.Session.GetString("title");
    var msg = Context.Session.GetString("msg");

    Context.Session.SetString("msgType", "");
    }*@
@if (!string.IsNullOrEmpty(Context.Session.GetString(Helper.MsgType)))
{
if (Context.Session.GetString(Helper.MsgType) == Helper.Success)
{
<script>

    Swal.fire({
        title: '@Context.Session.GetString(Helper.Title)',
        text: '@Html.Raw(Context.Session.GetString(Helper.Msg))',
        confirmButtonText: '@Html.Raw(WebResource.OkMsg)',
        icon: '@Html.Raw(Helper.Success)'
    });
</script>
}
else{
<script>
    Swal.fire({
        title: '@Context.Session.GetString(Helper.Title)',
        text: '@Html.Raw(Context.Session.GetString(Helper.Msg))',
        confirmButtonText: '@Html.Raw(WebResource.OkMsg)',
        icon: '@Html.Raw(Helper.Error)'
    });

</script>
}
Context.Session.SetString(Helper.MsgType, "");
}

<script src="~/Modules/Roles.js"></script>

<script>
    let EditBtn = '@Html.Raw(WebResource.EditBtn)';
    let EditUserRole = '@Html.Raw(WebResource.EditUserRole)';
    let CreateNewRole = '@Html.Raw(WebResource.CreateNewRoleBtn)';
    let SaveBtn = '@Html.Raw(WebResource.SaveBtn)';

    let UserImgPath = '@Html.Raw(Helper.UserImgPath)';
    let SuccessWord = '@Html.Raw(Helper.Success)';

    let DeleteConfirm = '@Html.Raw(WebResource.Delete)';
    let DeleteRoleMsg = '@Html.Raw(WebResource.DeleteRoleMsg)';
    let AreYouSure = '@Html.Raw(WebResource.AreYouSure)';
    let AreYouSureMsg = '@Html.Raw(WebResource.AreYouSureMsg)';
    let YesBtn = '@Html.Raw(WebResource.YesBtn)';
    let NoBtn = '@Html.Raw(WebResource.NoBtn)';
</script>
}